---
name: Check üõ†

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  audit:
    name: Audit Dependencies üïµÔ∏è‚Äç‚ôÇÔ∏è
    uses: insightsengineering/r.pkg.template/.github/workflows/audit.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
  r-cmd:
    name: R CMD Check üß¨
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        _R_CHECK_CRAN_INCOMING_REMOTE_=false
        TESTING_DEPTH=5
        _R_CHECK_EXAMPLE_TIMING_THRESHOLD_=6
      additional-r-cmd-check-params: --as-cran
      enforce-note-blocklist: true
      note-blocklist: |
        checking dependencies in R code .* NOTE
        checking R code for possible problems .* NOTE
        checking examples .* NOTE
        checking Rd line widths .* NOTE
        checking S3 generic/method consistency .* NOTE
        checking Rd .usage sections .* NOTE
        checking for unstated dependencies in vignettes .* NOTE
        checking top-level files .* NOTE
      unit-test-report-brand: >-
        https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/thumbs/teal.png
      deps-installation-method: setup-r-dependencies
      lookup-refs: |
        insightsengineering/teal.data
        insightsengineering/teal.slice
        insightsengineering/teal.code
        insightsengineering/teal.logger
        insightsengineering/teal.reporter
        insightsengineering/teal.widgets
  r-cmd-non-cran:
    name: R CMD Check (non-CRAN) üß¨
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        _R_CHECK_EXAMPLE_TIMING_THRESHOLD_=6
        NOT_CRAN=true
      enforce-note-blocklist: true
      concurrency-group: non-cran
      unit-test-report-directory: unit-test-report-non-cran
      note-blocklist: |
        checking dependencies in R code .* NOTE
        checking R code for possible problems .* NOTE
        checking examples .* NOTE
        checking Rd line widths .* NOTE
        checking S3 generic/method consistency .* NOTE
        checking Rd .usage sections .* NOTE
        checking for unstated dependencies in vignettes .* NOTE
        checking top-level files .* NOTE
      deps-installation-method: setup-r-dependencies
      lookup-refs: |
        insightsengineering/teal.data
        insightsengineering/teal.slice
        insightsengineering/teal.code
        insightsengineering/teal.logger
        insightsengineering/teal.reporter
        insightsengineering/teal.widgets
  coverage:
    name: Coverage üìî
    uses: insightsengineering/r.pkg.template/.github/workflows/test-coverage.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        NOT_CRAN=true
      deps-installation-method: setup-r-dependencies
      lookup-refs: |
        insightsengineering/teal.data
        insightsengineering/teal.slice
        insightsengineering/teal.code
        insightsengineering/teal.logger
        insightsengineering/teal.reporter
        insightsengineering/teal.widgets
  linter:
    if: github.event_name != 'push'
    name: SuperLinter ü¶∏‚Äç‚ôÄÔ∏è
    uses: insightsengineering/r.pkg.template/.github/workflows/linter.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
  roxygen:
    name: Roxygen üÖæ
    uses: insightsengineering/r.pkg.template/.github/workflows/roxygen.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      auto-update: true
      deps-installation-method: setup-r-dependencies
      lookup-refs: |
        insightsengineering/teal.data
        insightsengineering/teal.slice
        insightsengineering/teal.code
        insightsengineering/teal.logger
        insightsengineering/teal.reporter
        insightsengineering/teal.widgets
  gitleaks:
    name: gitleaks üíß
    uses: insightsengineering/r.pkg.template/.github/workflows/gitleaks.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
  spelling:
    name: Spell Check üÜé
    uses: insightsengineering/r.pkg.template/.github/workflows/spelling.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  links:
    if: github.event_name != 'push'
    name: Check URLs üåê
    uses: insightsengineering/r.pkg.template/.github/workflows/links.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
  vbump:
    name: Version Bump ü§úü§õ
    if: github.event_name == 'push'
    uses: insightsengineering/r.pkg.template/.github/workflows/version-bump.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  version:
    name: Version Check üèÅ
    uses: insightsengineering/r.pkg.template/.github/workflows/version.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
  licenses:
    name: License Check üÉè
    uses: insightsengineering/r.pkg.template/.github/workflows/licenses.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
  style:
    if: github.event_name != 'push'
    name: Style Check üëó
    uses: insightsengineering/r.pkg.template/.github/workflows/style.yaml@fd11bcdd25b3d8904e574c2becc3f72df9add7fc
    with:
      auto-update: true
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
